/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package group6;

/**
 *
 * @author ryan1
 */
public class NewCustomer extends javax.swing.JFrame {

    static String user;
    static String pass;
    static Database db;
    /**
     * Creates new form NewCustomer
     */
    public NewCustomer(String u, String p, Database data) {
        initComponents();
        user = u;
        pass = p;
        db = data;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        financed_leased_bought = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        first_name = new javax.swing.JTextField();
        last_name = new javax.swing.JTextField();
        middle_initial = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        zip_code = new javax.swing.JTextField();
        home_phone = new javax.swing.JTextField();
        work_phone = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        ssn = new javax.swing.JTextField();
        rb_lease = new javax.swing.JRadioButton();
        Financed = new javax.swing.JRadioButton();
        Purchased = new javax.swing.JRadioButton();
        transaction_date = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        save_record = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        income = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Automobile Sales Manager");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Customer Information");

        jLabel3.setText("First Name:");

        jLabel4.setText("Last Name:");

        jLabel5.setText("Middle Initial:");

        jLabel6.setText("Address:");

        jLabel7.setText("Zip Code:");

        jLabel8.setText("Home Phone:");

        jLabel9.setText("Work Phone:");

        jLabel10.setText("E-mail Address:");

        jLabel11.setText("Social Security Number: ");

        zip_code.setToolTipText("");

        financed_leased_bought.add(rb_lease);
        rb_lease.setText("Leased");

        financed_leased_bought.add(Financed);
        Financed.setText("Financed");

        financed_leased_bought.add(Purchased);
        Purchased.setText("Purchased");

        jLabel12.setText("Date of Transaction:");

        save_record.setText("Save");
        save_record.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_recordActionPerformed(evt);
            }
        });

        jLabel13.setText("Income:");

        income.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(save_record)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(income, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(64, 64, 64)
                                .addComponent(transaction_date))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel11)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(ssn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel10)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(work_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(home_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(zip_code, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(middle_initial, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(last_name, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(117, 117, 117)
                                            .addComponent(first_name, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap(103, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rb_lease)
                        .addGap(18, 18, 18)
                        .addComponent(Financed)
                        .addGap(18, 18, 18)
                        .addComponent(Purchased)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(first_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(last_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(middle_initial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(zip_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(home_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(work_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(ssn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(income, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_lease)
                    .addComponent(Financed)
                    .addComponent(Purchased))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(transaction_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addComponent(save_record)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void incomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incomeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_incomeActionPerformed

    private void save_recordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_recordActionPerformed
        // TODO add your handling code here:
        Customer primary = new Customer(); //create objects for the applicant
        //boolean invalid = false; //if boolean invalid is true, application status marked as invalid and calculations suspended
        
        primary.setFirst(first_name.getText());
        primary.setLast(last_name.getText());
        primary.setMiddle(middle_initial.getText());
        primary.setAddress(address.getText());
        primary.setZip(zip_code.getText());
        primary.setHome(home_phone.getText());
        primary.setWork(work_phone.getText());
        primary.setEmail(email.getText());
        primary.setSocial(ssn.getText());
        if(rb_lease.isSelected())
            primary.setOS(Customer.ownStatus.leased);
        else if(Financed.isSelected())
            primary.setOS(Customer.ownStatus.financed);
        else if(Purchased.isSelected())
            primary.setOS(Customer.ownStatus.purchased);
        primary.setDate(transaction_date.getText());
        primary.setIncome(income.getText());
        
        db.Database(user, pass, -1, primary);
        
        setVisible(false);
        
        //testing
        /*first_name.setText("test" + primary.getFirst());
        last_name.setText("test" + primary.getLast());
        middle_initial.setText("test" + primary.getMiddle());
        address.setText("test" + primary.getAddress());
        zip_code.setText("test" + primary.getZip());
        home_phone.setText("test" + primary.getHome());
        work_phone.setText("test" + primary.getWork());
        email.setText("test" + primary.getEmail());
        ssn.setText("test" + primary.getSocial());
        transaction_date.setText("test" + primary.getDate());
        income.setText("test" + primary.getIncome());*/
        
    }//GEN-LAST:event_save_recordActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         


        //obtain data from the text field and store; check if valid
       /* primary.setIncome(Float.parseFloat(jTextField8.getText()));
        if(!primary.validFloat(primary.getIncome(), 0, 1000000000))
        {
            jTextField8.setText("INVALID");
            invalid=true;
        }*/
        
        //obtain data from the text field and store; check if valid
       /* primary.setPayment(Float.parseFloat(jTextField10.getText()));
        if(!primary.validFloat(primary.getPayment(), 0, 1000000000))
        {
            jTextField10.setText("INVALID");
            invalid=true;
        }*/
        
        //obtain data from the text field and store; check if valid
        /*primary.setCarCost(Float.parseFloat(jTextField12.getText()));
        if(!primary.validFloat(primary.getCarCost(), 0, 2000000000))
        {
            jTextField12.setText("INVALID");
            invalid=true;
        }*/
        
        //obtain data from the text field and store; check if valid
        /*primary.setTradeIn(Float.parseFloat(jTextField13.getText()));
        if(!primary.validFloat(primary.getTradeIn(), 0, 2000000000))
        {
            jTextField13.setText("INVALID");
            invalid=true;
        }*/

        //obtain data from the text field and store; check if valid
        /*primary.setDownPayment(Float.parseFloat(jTextField14.getText()));
        if(!primary.validFloat(primary.getDownPayment(), 0, 2000000000))
        {
            jTextField14.setText("INVALID");
            invalid=true;
        }*/
        
        //obtain data from the text field and store; check if valid
        /*primary.setNumberYears(Integer.parseInt(jTextField15.getText()));
        if(!primary.validFloat(primary.getNumberYears(), 0, 99))
        {
            jTextField15.setText("INVALID");
            invalid=true;
        }*/

        //obtain data from the text field and store; check if valid
        /*primary.setCredit(Integer.parseInt(jTextField16.getText()));
        if(!primary.validFloat(primary.getCredit(), 0, 900))
        {
            jTextField16.setText("INVALID");
            invalid=true;
        }*/
        
        /*if(invalid) //if invalid, stop calculations
            jTextField24.setText("INVALID");
        else
        {
            if(!primary.goodCredit()) //if bad credit, deny
               jTextField24.setText("Denied");
            else{ //if good credit, approve, calculate, and output
               jTextField24.setText("Approved!"); 
               primary.calculate(spouse.getIncome(), spouse.getPayment());
        
               jTextField17.setText("$"+String.format("%.2f", primary.getIncomes()));
               jTextField18.setText("$"+String.format("%.2f", primary.getPayments()));
               jTextField19.setText("$"+String.format("%.2f", primary.getPaymentIncome()));
               jTextField20.setText((String.format("%.2f", primary.getInterest()*100))+"%");
               jTextField21.setText("$"+String.format("%.2f", primary.getCarCost()));
               jTextField22.setText("$"+String.format("%.2f", primary.getMonthlyPayment()));
               jTextField23.setText(Integer.toString(primary.getLastDate()));
            }
        }*/
    }                                        
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewCustomer(user, pass, db).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Financed;
    private javax.swing.JRadioButton Purchased;
    private javax.swing.JTextField address;
    private javax.swing.JTextField email;
    private javax.swing.ButtonGroup financed_leased_bought;
    private javax.swing.JTextField first_name;
    private javax.swing.JTextField home_phone;
    private javax.swing.JTextField income;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField last_name;
    private javax.swing.JTextField middle_initial;
    private javax.swing.JRadioButton rb_lease;
    private javax.swing.JButton save_record;
    private javax.swing.JTextField ssn;
    private javax.swing.JFormattedTextField transaction_date;
    private javax.swing.JTextField work_phone;
    private javax.swing.JTextField zip_code;
    // End of variables declaration//GEN-END:variables
}
